//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFerMex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int ID_EMPLEADO { get; set; }
        public string NOMBRE { get; set; }
        public string AP_PAT { get; set; }
        public string AP_MAT { get; set; }
        public string CORREO { get; set; }
        public string ROL { get; set; }
        public string DEPARTAMENTO { get; set; }
    }
}
