//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFerMex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ordenCliente()
        {
            this.ordenProducto = new HashSet<ordenProducto>();
        }
    
        public int ID_ORDEN_CLIENTE { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public int NUM_CONFIRMACION { get; set; }
        public int TOTAL { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<int> ID_DIRENTREGA { get; set; }
        public Nullable<int> ID_PAQUETERIA { get; set; }
        public Nullable<int> NUM_GUIA { get; set; }
        public Nullable<System.DateTime> FECHA_ENVIO { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Paqueteria Paqueteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenProducto> ordenProducto { get; set; }
    }
}
